module.exports = {

    //GENERAL
    INTERNAL_ERROR_MESSAGE: "INTERNAL_ERROR",
    NOT_FOUND_ERROR_MESSAGE: "NOT_FOUND",
    SUCCEEDED_MESSAGE: "SUCCEEDED",

    //VALIDATION
    INVALID_PARAMETER_SENDED:'FAILED',
  };
